name: bitcoin_bip32
version: 0.1.1
description: Library implementing Bitcoins BIP32 (Hierarchical Deterministic key derivation) specification in a Flutter friendly fashion.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bitcoin_bip32

dependencies:
    pointycastle: ^1.0.0-rc4
    base58check: ^1.0.1
    convert: ^2.0.2

dev_dependencies:
    test: ^1.3.4

environment:
    sdk: ">=2.0.0 <3.0.0"
